# Generated by Django 3.0.4 on 2020-03-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=264)),
                ('Role', models.CharField(max_length=264)),
                ('Credit', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Team2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=264)),
                ('Role', models.CharField(max_length=264)),
                ('Credit', models.CharField(max_length=264)),
            ],
        ),
    ]
