# Generated by Django 3.0.4 on 2020-03-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamPicker', '0002_auto_20200327_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player_List',
        ),
    ]
