# Generated by Django 3.0.4 on 2020-03-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamPicker', '0004_player_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Credit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='Role',
            field=models.CharField(choices=[('BAT', 'BAT'), ('BOWL', 'BOWL'), ('ALL', 'ALL'), ('WK', 'WK')], default='BAT', max_length=264),
        ),
        migrations.AlterField(
            model_name='player',
            name='Team',
            field=models.CharField(choices=[('Team1', 'Team1'), ('Team2', 'Team2')], default='Team1', max_length=264),
        ),
        migrations.AlterField(
            model_name='series',
            name='Match',
            field=models.CharField(max_length=264, unique=True),
        ),
    ]
