# Generated by Django 3.0.7 on 2020-06-13 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamPicker', '0005_auto_20200331_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=264)),
                ('Role', models.CharField(choices=[('BAT', 'BAT'), ('BOWL', 'BOWL'), ('ALL', 'ALL'), ('WK', 'WK')], default='BAT', max_length=264)),
                ('Credit', models.FloatField()),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='TeamPicker.Team')),
            ],
        ),
    ]
